namespace VirtualTryOn.Api.DTOs.Auth;

public sealed record UserProfileResponse(
    Guid Id,
    string FullName,
    string Email,
    string Gender,
    string? PhoneNumber,
    string? ProfilePhotoUrl,
    string? FullBodyPhotoUrl,
    string? UpperBodyPhotoUrl,
    string? LowerBodyPhotoUrl,
    string? FacePhotoUrl,
    decimal? HeightCm,
    decimal? WeightKg,
    string? PreferredSize,
    string? BodyShape,
    string? ShoeSize,
    string? TopSize,
    string? BottomSize,
    string Role,
    bool IsEmailVerified,
    DateOnly? DateOfBirth,
    DateTimeOffset CreatedAt,
    DateTimeOffset? UpdatedAt);
